name: Bug Report
description: Create a report to help us improve
labels: ["Type: Bug"]
body:
  - type: dropdown
    id: version
    attributes:
      label: Gloo Mesh Version
      description: What version of Gloo Mesh are you using?
      options:
        - 1.3.x (beta)
        - 1.2.x (latest stable)
        - 1.1.x
        - 1.0.x
    validations:
      required: true
  - type: dropdown
    id: istio-version
    attributes:
      label: Istio Version
      description: (Optional) Please indicate the version of Istio in use
      options:
        - 1.12.x 
        - 1.11.x
        - 1.10.x
        - 1.9.x
        - 1.8.x
        - 1.7.x
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      placeholder: Add a clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce the bug
      placeholder: |
        1. kube apply '...'
        2. curl '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      placeholder: When I performed x, I expected y to happen
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      placeholder: |
        - Customer or prospect
        - Kubernetes version
