blank_issues_enabled: false
contact_links:
  - name: Solo.io Slack
    url: https://slack.solo.io
    about: For a fast response, consider asking your question on the Solo slack.
      Also, please check out `https://docs.solo.io/gloo-mesh/latest` for documentation and guides.
